name: Publish ClickOnce

on:
  push:
    branches:
      - main  # Define o branch que aciona o workflow
    tags:
      - 'v*'  # Aciona quando uma tag é criada (e.g., v1.5.4)

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Fazer o checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Instalar o .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      # 3. Instalar o GitVersion
      - name: Setup GitVersion
        uses: gitversion/gitversion-action@v0.9.0  # Correção: Usando a ação correta para GitVersion

      # 4. Restaurar pacotes NuGet (caminho relativo à pasta src)
      - name: Restore NuGet packages
        run: dotnet restore ./src/SGI.csproj

      # 5. Obter a versão gerada pelo GitVersion
      - name: Get version from GitVersion
        id: gitversion
        run: echo "VERSION=$(GitVersion /showvariable SemVer)" >> $GITHUB_ENV  # Guarda a versão no ambiente

      # 6. Atualizar o arquivo .csproj com a nova versão
      - name: Update .csproj version
        run: |
          sed -i 's/<Version>.*<\/Version>/<Version>${{ env.VERSION }}<\/Version>/' ./src/SGI.csproj
          sed -i 's/<AssemblyVersion>.*<\/AssemblyVersion>/<AssemblyVersion>${{ env.VERSION }}<\/AssemblyVersion>/' ./src/SGI.csproj
          sed -i 's/<FileVersion>.*<\/FileVersion>/<FileVersion>${{ env.VERSION }}<\/FileVersion>/' ./src/SGI.csproj

      # 7. Compilar o projeto (caminho relativo à pasta src)
      - name: Build the project
        run: dotnet build ./src/SGI.csproj --configuration Release

      # 8. Publicar ClickOnce (caminho relativo à pasta src)
      - name: Publish ClickOnce
        run: dotnet publish ./src/SGI.csproj --configuration Release --output ./src/publish

      # 9. Fazer upload do instalador para os artefatos do GitHub (versão atualizada)
      - name: Upload installer
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: ClickOnce
          path: ./src/publish/*

      # 10. Criar uma nova release no GitHub
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ./src/publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
