name: Publish ClickOnce

on:
  push:
    tags:
      - '[0-9]+.*'  # Aciona no push de tags, por exemplo: 1.5.4

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Fazer o checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Instalar o .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      # 3. Restaurar pacotes NuGet (caminho relativo à pasta src)
      - name: Restore NuGet packages
        run: dotnet restore ./src/SGI.csproj

      # 4. Compilar o projeto (caminho relativo à pasta src)
      - name: Build the project
        run: dotnet build ./src/SGI.csproj --configuration Release

      # 5. Publicar ClickOnce (caminho relativo à pasta src)
      - name: Publish ClickOnce
        run: dotnet publish ./src/SGI.csproj --configuration Release --output ./src/publish

      # 6. Compactar os arquivos em publish.zip
      - name: Zip publish folder
        run: Compress-Archive -Path ./src/publish/* -DestinationPath ./src/publish/publish.zip

      # 7. Fazer upload do publish.zip para os artefatos do GitHub
      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: ClickOnce
          path: ./src/publish/publish.zip

      # 8. Criar uma nova release no GitHub
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ./src/publish/publish.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
