name: Publish ClickOnce

on:
  push:
    branches:
      - main  # Aciona o CI/CD ao fazer push na branch main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      # 1. Fazer o checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4  # Usando a versão mais recente

      # 2. Cache de pacotes NuGet para melhorar a performance
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # 3. Instalar o .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 4. Restaurar pacotes NuGet (caminho relativo à pasta src)
      - name: Restore NuGet packages
        run: dotnet restore ./src/SGI.csproj

      # 5. Extrair versão do arquivo de projeto (.csproj) usando PowerShell
      - name: Get version from project file
        id: get_version
        run: |
          [xml]$csproj = Get-Content ./src/SGI.csproj
          $version = $csproj.Project.PropertyGroup.Version
          echo "VERSION=$version" >> $GITHUB_ENV

      # 6. Criar e enviar a tag (baseada na versão extraída, sem o prefixo 'v')
      - name: Create and push tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "${{ env.VERSION }}" -m "Version ${{ env.VERSION }}"
          git push origin "${{ env.VERSION }}"

      # 7. Compilar o projeto (caminho relativo à pasta src)
      - name: Build the project
        run: dotnet build ./src/SGI.csproj --configuration ${{ matrix.configuration }}

      # 8. Corrigir e validar código (analisar formatação de espaços em branco)
      - name: Format whitespace in the project
        run: dotnet format whitespace ./src/SGI.csproj --verify-no-changes

      # 9. Publicar ClickOnce **somente se for Release**
      - name: Publish ClickOnce (Release only)
        if: ${{ matrix.configuration == 'Release' }}  # Somente publica se for Release
        run: dotnet publish ./src/SGI.csproj --configuration Release --output ./src/publish

      # 10. Compactar os arquivos em publish.zip **somente se for Release**
      - name: Zip publish folder (Release only)
        if: ${{ matrix.configuration == 'Release' }}  # Somente compacta se for Release
        run: Compress-Archive -Path ./src/publish/* -DestinationPath ./src/publish/publish.zip

      # 11. Fazer upload do publish.zip para os artefatos do GitHub **somente se for Release**
      - name: Upload installer (Release only)
        if: ${{ matrix.configuration == 'Release' }}  # Somente faz upload se for Release
        uses: actions/upload-artifact@v4
        with:
          name: ClickOnce
          path: ./src/publish/publish.zip

      # 12. Criar uma nova release no GitHub **somente se for Release**
      - name: Create GitHub release (Release only)
        if: ${{ matrix.configuration == 'Release' }}  # Somente cria release se for Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./src/publish/publish.zip
          tag_name: ${{ env.VERSION }}  # Usando a tag que foi criada
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 13. Notificar o Discord (alerta de sucesso)
      - name: Send Discord notification (success)
        if: ${{ success() && matrix.configuration == 'Release' }}  # Notifica apenas em Release e sucesso
        run: |
          $webhookUrl = '${{ secrets.DISCORD_WEBHOOK_URL }}'
          $message = '{"content": "✅ Build and release successful for SGI (Release) on branch ''${{ github.ref_name }}''!"}'
          curl -H "Content-Type: application/json" -X POST -d $message $webhookUrl

      # 14. Notificar o Discord (alerta de falha)
      - name: Send Discord notification (failure)
        if: ${{ failure() }}
        run: |
          $webhookUrl = '${{ secrets.DISCORD_WEBHOOK_URL }}'
          $message = '{"content": "❌ Build failed for SGI on branch ''${{ github.ref_name }}''!"}'
          curl -H "Content-Type: application/json" -X POST -d $message $webhookUrl
